services:
  unbound:
    build:
      context: ./unbound
    container_name: unbound
    hostname: unbound
    volumes:
      - /etc/localtime:/etc/localtime:ro
#    ports:
      # It is not necessary to expose Unbound port 53 to the host,
      # since Pi-hole will access it through the internal Docker network.
      # If you need to test Unbound directly from the host, uncomment:
      # - "5053:53/tcp"
      # - "5053:53/udp"
    networks:
      dns_net:
        ipv4_address: 172.23.0.8
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "unbound-host", "-r", "-t", "A", "google.com", "@127.0.0.1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  pihole:
    container_name: pihole
    image: pihole/pihole:2025.04.0
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "90:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      - "443:443/tcp"
      # Uncomment the below if using Pi-hole as your DHCP Server
      #- "67:67/udp"
    environment:
      # Set the appropriate timezone for your location (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones), e.g:
      TZ: 'America/Sao_Paulo'
      # Set a password to access the web interface. Not setting one will result in a random password being assigned
      FTLCONF_webserver_api_password: 'your password'
      FTLCONF_dns_upstreams: '172.23.0.8#53'
      DNSMASQ_LISTENING: 'all'
    volumes:
      - './pihole/etc-pihole:/etc/pihole'
      - './pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      unbound:
        condition: service_started # or service_healthy
    cap_add:
      - NET_ADMIN
    networks:
      dns_net:
        ipv4_address: 172.23.0.7
    restart: unless-stopped

networks:
  dns_net:
    driver: bridge
    ipam:
        config:
        - subnet: 172.23.0.0/16
